import React from 'react';
import CharityQuizClient from '@/components/charity/CharityQuizClient';
import { ToastProvider } from '@/components/js/ToastContext';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cyber Free Rice 🐾 | Play Cybersecurity & Trivia Game to Feed Stray Animals',
  description: 'Answer cybersecurity, ethical hacking, and general knowledge trivia to donate real bowls of rice and fund warm meals for stray dogs in Patna. 100% free gamified charity.',
  keywords: [
    'Cyber Free Rice',
    'Free Rice Game',
    'Play Trivia Feed Animals',
    'Cybersecurity Quiz Game',
    'Play to Donate',
    'Charity Trivia Game',
    'Stray Animal Feeding Patna',
    'Gamified Ethical Hacking Quiz',
    'CyberKarma'
  ],
  openGraph: {
    title: 'Cyber Free Rice 🐾 — Play Trivia, Feed Real Stray Animals',
    description: 'Every correct answer generates free rice grains and funds warm street animal meals in Patna. Level up, build streaks, and play to make a real-world difference!',
    url: 'https://adityasec32.systems/charity-quiz',
    siteName: 'Cyber Free Rice & CyberKarma',
    images: [
      {
        url: 'https://adityasec32.systems/og_image.png',
        width: 1200,
        height: 630,
        alt: 'Cyber Free Rice — Gamified Trivia to Feed Animals',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Cyber Free Rice 🐾 — Play Trivia, Feed Real Stray Animals',
    description: 'Answer cybersecurity & trivia questions to donate real bowls of food to street animals. 100% Free & Impactful.',
    images: ['https://adityasec32.systems/og_image.png'],
  },
  alternates: {
    canonical: 'https://adityasec32.systems/charity-quiz',
  },
  manifest: '/manifest-quiz.json',
};

const jsonLdGame = {
  "@context": "https://schema.org",
  "@type": "Game",
  "name": "Cyber Free Rice",
  "description": "Gamified educational trivia platform where correct answers in cybersecurity, ecology, and science generate real-world rice donations for stray animals.",
  "genre": ["Educational Game", "Trivia", "Charity Game"],
  "gameItem": {
    "@type": "Thing",
    "name": "Grains of Rice"
  },
  "numberOfPlayers": {
    "@type": "QuantitativeValue",
    "value": 1
  },
  "url": "https://adityasec32.systems/charity-quiz",
  "author": {
    "@type": "Person",
    "name": "Aditya Jain",
    "url": "https://adityasec32.systems"
  }
};

const jsonLdFaq = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "How does Cyber Free Rice feed real animals?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Advertisers and ethical sponsors display non-intrusive ads on Cyber Free Rice. 100% of the ad revenue generated by users answering trivia questions is used to purchase rice, broth, and veterinary food distributed directly in daily street animal feeding drives in Patna, Bihar."
      }
    },
    {
      "@type": "Question",
      "name": "Is Cyber Free Rice free to play?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes! Cyber Free Rice is 100% free to play. You never need to pay any money; your correct trivia answers and time spent learning generate the revenue needed to feed animals."
      }
    },
    {
      "@type": "Question",
      "name": "What topics can I play on Cyber Free Rice?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "You can play multiple categories including Cybersecurity & Purple Teaming, Animal Welfare, Nature & Ecology, Science & Space, General Knowledge, and Humanities & Ethics."
      }
    }
  ]
};

export default function CharityQuizPage() {
  return (
    <ToastProvider>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdGame) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdFaq) }}
      />
      <CharityQuizClient />
    </ToastProvider>
  );
}
