import React from 'react';
import Link from 'next/link';
import { ArrowLeft, ShieldCheck, Heart, MapPin, CheckCircle2 } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About CyberKarma | Free Quiz Charity Feeding Street Animals in Patna',
  description: 'Learn how CyberKarma works. Every quiz answer generates Karma Points that fund real food for street dogs and animals in Patna, Bihar, field-verified by local volunteers.',
  alternates: { canonical: 'https://cyberkarma.me/about/' },
  openGraph: {
    title: 'About CyberKarma — Learn & Feed Street Animals',
    description: 'How does a free quiz feed street animals? Learn how CyberKarma converts ad revenue and quiz answers into real food for dogs in Patna, Bihar.',
    url: 'https://cyberkarma.me/about/',
  },
};

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-white p-6 sm:p-12 font-inter selection:bg-emerald-500/30">
      <div className="max-w-4xl mx-auto space-y-12">
        <div className="space-y-6">
          <Link href="/" className="inline-flex items-center gap-2 text-emerald-400 hover:text-emerald-300 transition-colors">
            <ArrowLeft size={16} /> Back to Home
          </Link>
          <h1 className="text-4xl sm:text-5xl font-black font-title">About CyberKarma</h1>
          <p className="text-lg text-slate-400 max-w-3xl leading-relaxed">
            CyberKarma is a free educational platform where every correct answer you submit directly helps feed street animals in Patna, Bihar. We believe in turning idle internet time into immediate, tangible real-world impact.
          </p>
        </div>

        <div className="grid sm:grid-cols-2 gap-8">
          <div className="bg-slate-900/50 p-8 rounded-3xl border border-white/10">
            <ShieldCheck size={32} className="text-emerald-400 mb-4" />
            <h2 className="text-2xl font-bold mb-3">How It Works</h2>
            <ul className="space-y-3 text-slate-300 font-mono text-sm">
              <li className="flex gap-2 items-start"><CheckCircle2 size={16} className="text-emerald-400 shrink-0 mt-1" /> <span>You play our free trivia quizzes.</span></li>
              <li className="flex gap-2 items-start"><CheckCircle2 size={16} className="text-emerald-400 shrink-0 mt-1" /> <span>Every correct answer generates 10 Karma Points.</span></li>
              <li className="flex gap-2 items-start"><CheckCircle2 size={16} className="text-emerald-400 shrink-0 mt-1" /> <span>At 200 Karma Points, a real bowl of Curd & Milk is funded by our sponsors.</span></li>
              <li className="flex gap-2 items-start"><CheckCircle2 size={16} className="text-emerald-400 shrink-0 mt-1" /> <span>Local volunteers in Patna purchase and distribute the food.</span></li>
            </ul>
          </div>
          <div className="bg-slate-900/50 p-8 rounded-3xl border border-white/10">
            <MapPin size={32} className="text-rose-400 mb-4" />
            <h2 className="text-2xl font-bold mb-3">Our Volunteers</h2>
            <p className="text-slate-300 font-mono text-sm leading-relaxed mb-4">
              Unlike abstract global charities, our impact is highly localized and documented. A dedicated network of local volunteers in the Patna Division executes daily evening and monsoon feeding drives.
            </p>
            <p className="text-slate-300 font-mono text-sm leading-relaxed">
              We focus on street dogs and vulnerable animals in areas like Rajbansi Nagar and Mohanpur Punaichak.
            </p>
          </div>
        </div>

        <div className="bg-emerald-950/20 p-8 rounded-3xl border border-emerald-500/20 flex flex-col items-center text-center">
          <Heart size={48} className="text-emerald-400 mb-4" />
          <h2 className="text-2xl font-bold mb-4">Where Does The Money Come From?</h2>
          <p className="text-slate-300 max-w-2xl leading-relaxed">
            CyberKarma is 100% free to play. The food is paid for using the ad revenue generated by the banner ads you see on the site, as well as direct corporate sponsorships from ethical security companies. You donate your time and knowledge, and we convert the ad revenue into milk and curd.
          </p>
        </div>
      </div>
    </main>
  );
}
