import React from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | CyberKarma',
  description: 'Read the CyberKarma Terms of Service. Karma Points hold no real-world monetary value and are used solely to track charitable impact donations.',
  alternates: { canonical: 'https://cyberkarma.me/terms/' },
};


export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-white p-6 sm:p-12 font-inter">
      <div className="max-w-3xl mx-auto space-y-8">
        <Link href="/" className="inline-flex items-center gap-2 text-emerald-400 hover:text-emerald-300">
          <ArrowLeft size={16} /> Back to Home
        </Link>
        <h1 className="text-3xl sm:text-4xl font-bold font-title">Terms of Service</h1>
        <div className="space-y-6 text-slate-300 text-sm leading-relaxed">
          <p>Last updated: July 2026</p>
          
          <h2 className="text-xl font-bold text-white mt-8">1. Acceptance of Terms</h2>
          <p>By accessing and using CyberKarma, you accept and agree to be bound by the terms and provision of this agreement.</p>
          
          <h2 className="text-xl font-bold text-white mt-8">2. Karma Points and Donations</h2>
          <p>The "Karma Points" and "Bowls of Curd & Milk" earned in the game are virtual representations of the charitable impact generated by ad revenue and sponsorships. They hold no real-world cash value and cannot be redeemed, transferred, or sold. The exact conversion of points to real-world food may fluctuate based on ad rates, food costs, and sponsor availability.</p>
          
          <h2 className="text-xl font-bold text-white mt-8">3. Intellectual Property</h2>
          <p>The content, organization, graphics, design, compilation, and other matters related to the Site are protected under applicable copyrights and intellectual property rights. The copying, redistribution, or publication by you of any such matters or any part of the Site is strictly prohibited without our consent.</p>

          <h2 className="text-xl font-bold text-white mt-8">4. Modifications to Service</h2>
          <p>CyberKarma Charity Foundation reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice at any time.</p>
        </div>
      </div>
    </main>
  );
}
